[package]
name = "inputforge-app"
autobins = false
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "inputforge"
path = "src/main.rs"

[dependencies]
inputforge-gui-dx    = { workspace = true }
inputforge-autostart = { workspace = true }
parking_lot          = { workspace = true }
tracing              = { workspace = true }
inputforge-core   = { workspace = true }
anyhow             = { workspace = true }
tracing-subscriber = { workspace = true }
mimalloc           = { workspace = true }
clap               = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
inputforge-core = {
    workspace = true,
    features = ["sdl3-input", "vjoy-output", "win32-io"],
}
tray-icon             = { workspace = true }
windows               = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
inputforge-core = { workspace = true, features = ["evdev-input", "uinput-output"] }

[lints]
workspace = true
